# Roteiro de apresentação

- Apresentação das bases
- Discussão das técnicas
- Metodologia
- Resultados
    - Melhores resultados de cada modelo
    - Comparação entre os modelos
- Conclusão

In [110]:
import pandas as pd
from scipy.stats import friedmanchisquare
import scikit_posthocs as sp

## KNN

In [102]:
knn_best12 = pd.read_csv("knn/sorted_unique.csv")
knn_results = pd.read_csv("knn/results.csv")
k_columns = [f"{k}k" for k in range(1,11)]
best_datasets = knn_best12["dataset"]


display(knn_best12)
display(knn_best12[k_columns].describe())

,dataset,split,1k,2k,3k,4k,5k,6k,7k,8k,9k,10k,k_mean,k_std
0,PCA_075_HOG_256_32x32.csv,70/30,0.716785,0.653405,0.729284,0.721024,0.720877,0.700766,0.683333,0.696267,0.674683,0.687209,0.698363,0.022931
1,PCA_075_HOG_128_16x16.csv,10-fold,0.663131,0.655532,0.671104,0.695736,0.672772,0.695134,0.677607,0.691864,0.680423,0.708564,0.681187,0.015620
2,PCA_090_HOG_256_32x32.csv,10-fold,0.688268,0.653216,0.688823,0.671519,0.689514,0.671558,0.687010,0.662512,0.701399,0.682671,0.679649,0.013842
3,HOG_256_32x32.csv,10-fold,0.665789,0.626836,0.687588,0.659834,0.680537,0.662212,0.690452,0.670818,0.701281,0.679078,0.672443,0.019711
4,PCA_090_HOG_128_16x16.csv,10-fold,0.660903,0.643490,0.673354,0.661611,0.656571,0.672257,0.662793,0.695374,0.674247,0.692563,0.669316,0.015069
5,PCA_075_HOG_128_32x32.csv,10-fold,0.652263,0.635696,0.667607,0.671451,0.673586,0.687657,0.664932,0.683398,0.657022,0.697269,0.669088,0.017125
6,PCA_090_HOG_128_32x32.csv,10-fold,0.651564,0.640820,0.640406,0.656340,0.643080,0.658431,0.664529,0.676632,0.661584,0.676605,0.656999,0.012690
7,HOG_128_16x16.csv,10-fold,0.657885,0.607913,0.667873,0.642932,0.647220,0.653291,0.653601,0.660841,0.659132,0.670397,0.652108,0.016754
8,HOG_128_32x32.csv,70/30,0.661144,0.664703,0.630277,0.633486,0.605392,0.652366,0.620238,0.663170,0.600304,0.648855,0.637994,0.022553
9,LBP_256_6R.csv,70/30,0.553586,0.603692,0.612426,0.611125,0.605492,0.610934,0.653452,0.633333,0.615333,0.616507,0.611588,0.023935
10,PCA_075_HOG_256_16x16.csv,10-fold,0.591808,0.510736,0.593946,0.563554,0.611512,0.589134,0.647121,0.631069,0.668269,0.634491,0.604164,0.043027
11,LBP_256_12R.csv,70/30,0.600111,0.589118,0.612561,0.582917,0.612561,0.619301,0.590986,0.598994,0.579086,0.581876,0.596751,0.013568

,1k,2k,3k,4k,5k,6k,7k,8k,9k,10k
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,0.646936,0.623763,0.656271,0.647628,0.651593,0.656087,0.658004,0.663689,0.656064,0.664674
std,0.044433,0.042526,0.039070,0.044793,0.037555,0.034322,0.028778,0.029614,0.038440,0.037316
min,0.553586,0.510736,0.593946,0.563554,0.605392,0.589134,0.590986,0.598994,0.579086,0.581876
25%,0.638701,0.606858,0.625848,0.627896,0.612299,0.644100,0.651869,0.653964,0.646600,0.645264
50%,0.659394,0.638258,0.667740,0.658087,0.651896,0.660321,0.663661,0.666994,0.664926,0.677842
75%,0.663795,0.653264,0.676913,0.671468,0.675324,0.676107,0.679038,0.685514,0.676118,0.688548
max,0.716785,0.664703,0.729284,0.721024,0.720877,0.700766,0.690452,0.696267,0.701399,0.708564

In [ ]:
knn_ranking = pd.DataFrame(
    {"mean": knn_best12[k_columns].mean(), "std": knn_best12[k_columns].std()}
)

knn_ranking.sort_values(by=["mean", "std"], ascending=[False, True])

         mean       std
10k  0.664674  0.037316
8k   0.663689  0.029614
7k   0.658004  0.028778
3k   0.656271  0.039070
6k   0.656087  0.034322
9k   0.656064  0.038440
5k   0.651593  0.037555
4k   0.647628  0.044793
1k   0.646936  0.044433
2k   0.623763  0.042526

## Árvore de decisão

In [49]:
dtree_results = pd.read_csv("dtree/results.csv", index_col=0)
dtree_configs = pd.read_csv("dtree/configs.csv", index_col=0)
dtree_conf_columns = [f"conf. {i}" for i in range(1,11)]
dtree_unique = dtree_results.drop_duplicates(subset=["dataset", "split"])

display(dtree_unique)
display(dtree_unique[dtree_conf_columns].describe())

,dataset,split,conf. 1,conf. 2,conf. 3,conf. 4,conf. 5,conf. 6,conf. 7,conf. 8,conf. 9,conf. 10
0,PCA_075_HOG_256_32x32.csv,10-fold,0.610033,0.606656,0.606210,0.606210,0.605023,0.605023,0.602752,0.602354,0.602354,0.601916
1,PCA_075_HOG_256_32x32.csv,70/30,0.575920,0.603333,0.633333,0.633333,0.624583,0.624583,0.606996,0.574882,0.574882,0.595489
4,PCA_075_HOG_128_16x16.csv,10-fold,0.664426,0.640556,0.638249,0.638249,0.637134,0.635714,0.632561,0.630013,0.630013,0.628732
5,PCA_075_HOG_128_16x16.csv,70/30,0.641948,0.624896,0.649734,0.649734,0.617908,0.624060,0.587149,0.624896,0.624896,0.603609
6,PCA_090_HOG_256_32x32.csv,10-fold,0.596060,0.595886,0.595886,0.594508,0.592648,0.592648,0.591725,0.589350,0.589350,0.588002
7,PCA_090_HOG_256_32x32.csv,70/30,0.591638,0.640443,0.640443,0.586919,0.591212,0.591212,0.595826,0.645532,0.645532,0.619346
10,HOG_256_32x32.csv,10-fold,0.626646,0.621824,0.618216,0.614912,0.614895,0.614097,0.614051,0.612840,0.612792,0.612312
11,HOG_256_32x32.csv,70/30,0.620827,0.649611,0.628644,0.631709,0.649976,0.645827,0.653439,0.645827,0.599750,0.633231
12,PCA_090_HOG_128_16x16.csv,10-fold,0.654456,0.646745,0.646745,0.642080,0.632887,0.632887,0.622385,0.617084,0.617084,0.615071
13,PCA_090_HOG_128_16x16.csv,70/30,0.604105,0.612332,0.612332,0.624896,0.624896,0.624896,0.575266,0.570707,0.570707,0.585185
14,PCA_075_HOG_128_32x32.csv,10-fold,0.609528,0.609528,0.607218,0.606037,0.604768,0.604613,0.604613,0.601135,0.601068,0.601003
15,PCA_075_HOG_128_32x32.csv,70/30,0.620827,0.620827,0.633308,0.633308,0.633308,0.590272,0.590272,0.637443,0.633308,0.636990
20,PCA_090_HOG_128_32x32.csv,10-fold,0.595302,0.595302,0.595047,0.595047,0.594438,0.594438,0.593800,0.593800,0.587775,0.587775
21,PCA_090_HOG_128_32x32.csv,70/30,0.555245,0.555245,0.548464,0.548464,0.582289,0.582289,0.595489,0.595489,0.628386,0.628386

,conf. 1,conf. 2,conf. 3,conf. 4,conf. 5,conf. 6,conf. 7,conf. 8,conf. 9,conf. 10
count,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000
mean,0.611926,0.615942,0.618131,0.614672,0.614712,0.611611,0.604737,0.610097,0.608421,0.609789
std,0.029562,0.025175,0.026987,0.027342,0.020244,0.019978,0.020370,0.024485,0.022753,0.017686
min,0.555245,0.555245,0.548464,0.548464,0.582289,0.582289,0.575266,0.570707,0.570707,0.585185
25%,0.595492,0.604164,0.606462,0.597795,0.597021,0.593096,0.592244,0.594222,0.591950,0.596868
50%,0.609781,0.616579,0.623430,0.619904,0.616402,0.609560,0.599289,0.607597,0.607573,0.607960
75%,0.625191,0.636556,0.637020,0.633327,0.630889,0.624818,0.612287,0.628734,0.627513,0.626126
max,0.664426,0.649611,0.649734,0.649734,0.649976,0.645827,0.653439,0.645827,0.645532,0.636990

In [48]:
dtree_ranking = pd.DataFrame(
    {
        "mean": dtree_unique[dtree_conf_columns].mean(),
        "std": dtree_unique[dtree_conf_columns].std(),
    }
)

dtree_ranking.sort_values(by=["mean", "std"], ascending=[False,True])

              mean       std
conf. 3   0.618131  0.026987
conf. 2   0.615942  0.025175
conf. 5   0.614712  0.020244
conf. 4   0.614672  0.027342
conf. 1   0.611926  0.029562
conf. 6   0.611611  0.019978
conf. 8   0.610097  0.024485
conf. 10  0.609789  0.017686
conf. 9   0.608421  0.022753
conf. 7   0.604737  0.020370

In [50]:
dtree_configs

,dataset,conf. 1,conf. 2,conf. 3,conf. 4,conf. 5,conf. 6,conf. 7,conf. 8,conf. 9,conf. 10
0,PCA_075_HOG_256_32x32.csv,"criterion=gini, max_depth=10","criterion=gini, max_depth=8","criterion=log_loss, max_depth=9","criterion=entropy, max_depth=9","criterion=entropy, max_depth=6","criterion=log_loss, max_depth=6","criterion=gini, max_depth=4","criterion=entropy, max_depth=8","criterion=log_loss, max_depth=8","criterion=log_loss, max_depth=7"
1,PCA_075_HOG_256_32x32.csv,"criterion=gini, max_depth=10","criterion=gini, max_depth=8","criterion=log_loss, max_depth=9","criterion=entropy, max_depth=9","criterion=entropy, max_depth=6","criterion=log_loss, max_depth=6","criterion=gini, max_depth=4","criterion=entropy, max_depth=8","criterion=log_loss, max_depth=8","criterion=log_loss, max_depth=7"
2,PCA_075_HOG_128_16x16.csv,"criterion=gini, max_depth=3","criterion=gini, max_depth=2","criterion=log_loss, max_depth=3","criterion=entropy, max_depth=3","criterion=gini, max_depth=4","criterion=gini, max_depth=5","criterion=gini, max_depth=14","criterion=entropy, max_depth=2","criterion=log_loss, max_depth=2","criterion=gini, max_depth=6"
3,PCA_090_HOG_256_32x32.csv,"criterion=gini, max_depth=4","criterion=entropy, max_depth=2","criterion=log_loss, max_depth=2","criterion=gini, max_depth=5","criterion=entropy, max_depth=8","criterion=log_loss, max_depth=8","criterion=gini, max_depth=6","criterion=entropy, max_depth=3","criterion=log_loss, max_depth=3","criterion=gini, max_depth=2"
4,PCA_090_HOG_256_32x32.csv,"criterion=gini, max_depth=4","criterion=entropy, max_depth=2","criterion=log_loss, max_depth=2","criterion=gini, max_depth=5","criterion=entropy, max_depth=8","criterion=log_loss, max_depth=8","criterion=gini, max_depth=6","criterion=entropy, max_depth=3","criterion=log_loss, max_depth=3","criterion=gini, max_depth=2"
5,HOG_256_32x32.csv,"criterion=gini, max_depth=10","criterion=gini, max_depth=12","criterion=gini, max_depth=9","criterion=gini, max_depth=2","criterion=gini, max_depth=5","criterion=gini, max_depth=14","criterion=gini, max_depth=13","criterion=gini, max_depth=15","criterion=gini, max_depth=11","criterion=gini, max_depth=6"
6,PCA_090_HOG_128_16x16.csv,"criterion=gini, max_depth=3","criterion=entropy, max_depth=3","criterion=log_loss, max_depth=3","criterion=gini, max_depth=2","criterion=entropy, max_depth=2","criterion=log_loss, max_depth=2","criterion=gini, max_depth=5","criterion=entropy, max_depth=4","criterion=log_loss, max_depth=4","criterion=gini, max_depth=6"
7,PCA_075_HOG_128_32x32.csv,"criterion=log_loss, max_depth=4","criterion=entropy, max_depth=4","criterion=gini, max_depth=14","criterion=gini, max_depth=13","criterion=gini, max_depth=12","criterion=entropy, max_depth=7","criterion=log_loss, max_depth=7","criterion=gini, max_depth=11","criterion=gini, max_depth=15","criterion=gini, max_depth=9"
8,HOG_256_32x32.csv,"criterion=gini, max_depth=10","criterion=gini, max_depth=12","criterion=gini, max_depth=9","criterion=gini, max_depth=2","criterion=gini, max_depth=5","criterion=gini, max_depth=14","criterion=gini, max_depth=13","criterion=gini, max_depth=15","criterion=gini, max_depth=11","criterion=gini, max_depth=6"
9,PCA_075_HOG_128_16x16.csv,"criterion=gini, max_depth=3","criterion=gini, max_depth=2","criterion=log_loss, max_depth=3","criterion=entropy, max_depth=3","criterion=gini, max_depth=4","criterion=gini, max_depth=5","criterion=gini, max_depth=14","criterion=entropy, max_depth=2","criterion=log_loss, max_depth=2","criterion=gini, max_depth=6"
10,PCA_090_HOG_128_32x32.csv,"criterion=log_loss, max_depth=7","criterion=entropy, max_depth=7","criterion=entropy, max_depth=11","criterion=log_loss, max_depth=11","criterion=log_loss, max_depth=4","criterion=entropy, max_depth=4","criterion=entropy, max_depth=5","criterion=log_loss, max_depth=5","criterion=log_loss, max_depth=15","criterion=entropy, max_depth=15"
11,PCA_075_HOG_128_32x32.csv,"criterion=log_loss, max_depth=4","criterion=entropy, max_depth=4","criterion=gini, max_depth=14","criterion=gini, max_depth=13","criterion=gini, max_depth=12","criterion=entropy, max_depth=7","criterion=log_loss, max_depth=7","criterion=gini, max_depth=11","criterion=gini, max_depth=15","criterion=gini, max_depth=9"

## Naive Bayes

## MLP

In [63]:
mlp_results = pd.read_csv("mlp/final_results.csv")
mlp_configs = pd.read_csv("mlp/sorted.csv")
mlp_conf_columns = [f"conf {i}" for i in range(10)]

display(mlp_results)
display(mlp_results.describe())
display(mlp_configs)

,dataset,split,conf 0,conf 1,conf 2,conf 3,conf 4,conf 5,conf 6,conf 7,conf 8,conf 9
0,PCA_075_HOG_256_32x32.csv,10-fold CV,0.725878,0.719678,0.693762,0.765110,0.727500,0.712291,0.671989,0.728582,0.707478,0.720775
1,PCA_075_HOG_256_32x32.csv,70/30,0.734701,0.684392,0.700030,0.744866,0.664958,0.674634,0.695023,0.700030,0.685024,0.679904
2,PCA_075_HOG_128_16x16.csv,10-fold CV,0.698133,0.675982,0.693053,0.691012,0.704154,0.673156,0.668693,0.705667,0.694192,0.684299
3,PCA_075_HOG_128_16x16.csv,70/30,0.674634,0.659898,0.688912,0.649895,0.700000,0.660000,0.704431,0.700000,0.674959,0.689752
4,PCA_090_HOG_256_32x32.csv,10-fold CV,0.685858,0.707137,0.705527,0.718078,0.726572,0.703299,0.716309,0.716748,0.699411,0.690410
5,PCA_090_HOG_256_32x32.csv,70/30,0.621616,0.698095,0.674634,0.704667,0.704845,0.648309,0.724966,0.689534,0.689752,0.669205
6,HOG_256_32x32.csv,10-fold CV,0.701658,0.478810,0.723681,0.579769,0.701349,0.342840,0.545515,0.712871,0.415538,0.698492
7,HOG_256_32x32.csv,70/30,0.684834,0.518068,0.744713,0.674634,0.689907,0.344503,0.520725,0.670000,0.322282,0.664824
8,PCA_090_HOG_128_16x16.csv,10-fold CV,0.679849,0.701761,0.701474,0.714753,0.701688,0.689899,0.695184,0.689707,0.685526,0.687447
9,PCA_090_HOG_128_16x16.csv,70/30,0.585118,0.590041,0.704667,0.660000,0.684645,0.645027,0.714850,0.619886,0.654611,0.623898
10,PCA_075_HOG_128_32x32.csv,10-fold CV,0.719920,0.691863,0.698093,0.712178,0.701340,0.676453,0.702834,0.688225,0.681880,0.696098
11,PCA_075_HOG_128_32x32.csv,70/30,0.720028,0.704668,0.700000,0.715021,0.719326,0.674959,0.715021,0.724855,0.715021,0.719579
12,PCA_090_HOG_128_32x32.csv,10-fold CV,0.739243,0.733379,0.706749,0.741325,0.718285,0.734075,0.711846,0.731340,0.700182,0.732627
13,PCA_090_HOG_128_32x32.csv,70/30,0.684961,0.719579,0.710000,0.724192,0.715021,0.754871,0.714450,0.694840,0.715021,0.744508
14,HOG_128_16x16.csv,10-fold CV,0.687458,0.419207,0.716181,0.580602,0.690165,0.462475,0.512645,0.693892,0.375287,0.683736
15,HOG_128_16x16.csv,70/30,0.685024,0.322282,0.729919,0.685024,0.684961,0.649159,0.494431,0.685024,0.322282,0.670033
16,HOG_128_32x32.csv,10-fold CV,0.721007,0.653005,0.616785,0.720749,0.727185,0.637704,0.355447,0.733967,0.660423,0.716001
17,HOG_128_32x32.csv,70/30,0.699760,0.721955,0.639892,0.698095,0.710000,0.727294,0.322282,0.719579,0.710000,0.714679
18,LBP_256_6R.csv,10-fold CV,0.368818,0.604783,0.352294,0.621256,0.481701,0.588979,0.323600,0.523731,0.616879,0.598662
19,LBP_256_6R.csv,70/30,0.344503,0.596008,0.322282,0.619429,0.557880,0.606848,0.344503,0.564162,0.589625,0.584782
20,PCA_075_HOG_256_16x16.csv,10-fold CV,0.624088,0.663670,0.692355,0.672089,0.708471,0.673475,0.671103,0.705001,0.657463,0.658621
21,PCA_075_HOG_256_16x16.csv,70/30,0.599880,0.645027,0.644600,0.625028,0.709301,0.650000,0.670000,0.640036,0.645027,0.610000
22,LBP_256_12R.csv,10-fold CV,0.449411,0.616680,0.352291,0.598934,0.557293,0.602849,0.317289,0.579751,0.593920,0.605160
23,LBP_256_12R.csv,70/30,0.344503,0.565888,0.322282,0.623444,0.574179,0.598068,0.322282,0.580042,0.590041,0.595030

,conf 0,conf 1,conf 2,conf 3,conf 4,conf 5,conf 6,conf 7,conf 8,conf 9
count,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000
mean,0.632537,0.628827,0.634757,0.676673,0.677530,0.630465,0.576476,0.674894,0.616743,0.672438
std,0.124739,0.104332,0.138850,0.053486,0.065028,0.106289,0.160300,0.058703,0.124824,0.046454
min,0.344503,0.322282,0.322282,0.579769,0.481701,0.342840,0.317289,0.523731,0.322282,0.584782
25%,0.616182,0.594516,0.643423,0.624632,0.684882,0.605848,0.459685,0.662509,0.592950,0.649940
50%,0.684992,0.661784,0.695928,0.688018,0.701519,0.655000,0.670551,0.694366,0.667691,0.684017
75%,0.706223,0.702488,0.705833,0.715786,0.711255,0.679814,0.706285,0.713840,0.695497,0.702539
max,0.739243,0.733379,0.744713,0.765110,0.727500,0.754871,0.724966,0.733967,0.715021,0.744508

,hidden_layer_sizes,solver,learning_rate_init,max_iter,activation,f1_weighted
0,59,adam,0.0001,2500,relu,0.764546
1,59,adam,0.1000,3000,relu,0.749624
2,18,sgd,0.0010,1000,relu,0.740000
3,59,adam,0.0100,2000,relu,0.740000
4,59,sgd,0.0100,1000,relu,0.734967
5,59,adam,0.1000,1500,relu,0.730027
6,59,sgd,0.0001,1000,relu,0.729784
7,59,sgd,0.0100,1500,relu,0.724855
8,18,adam,0.1000,2500,relu,0.724690
9,59,adam,0.0010,2500,relu,0.720028

In [62]:
mlp_ranking = pd.DataFrame(
    {
        "mean": mlp_results[mlp_conf_columns].mean(),
        "std": mlp_results[mlp_conf_columns].std(),
    }
)

mlp_ranking.sort_values(by=["mean", "std"], ascending=[False, True])

            mean       std
conf 4  0.677530  0.065028
conf 3  0.676673  0.053486
conf 7  0.674894  0.058703
conf 9  0.672438  0.046454
conf 2  0.634757  0.138850
conf 0  0.632537  0.124739
conf 5  0.630465  0.106289
conf 1  0.628827  0.104332
conf 8  0.616743  0.124824
conf 6  0.576476  0.160300

## Teste estatístico dos classificadores individuais

In [111]:
# gambiarra
from scipy.stats import friedmanchisquare


knn_24 = dtree_results[["dataset", "split"]].merge(
    knn_results,
    on=["dataset", "split"],
    how="left"
)


individual_models = pd.DataFrame({
    "mlp": mlp_results["conf 4"],
    "knn": knn_24["10k"],
    "dtree": dtree_results["conf. 3"]
})

stat, p = friedmanchisquare(*[individual_models[col] for col in individual_models.columns])

print("p-value:", p)

if p < 0.05:
    posthoc = sp.posthoc_nemenyi_friedman(individual_models.values)
    posthoc.index = individual_models.columns
    posthoc.columns = individual_models.columns

    print(posthoc)

p-value: 3.1545438051702596e-06
            mlp       knn     dtree
mlp    1.000000  0.832229  0.000012
knn    0.832229  1.000000  0.000157
dtree  0.000012  0.000157  1.000000

## Classificadores

### Bagging

In [113]:
bagging_results = pd.read_csv("results/bagging_table.csv", index_col=0)
rf_results = pd.read_csv("results/rf_table.csv", index_col=0)
stacking_results = pd.read_csv("results/stacking_table.csv", index_col=0)
voting_results = pd.read_csv("results/voting_table.csv", index_col=0)

display(bagging_results)

,Unnamed: 1,Unnamed: 2,k-NN (10),k-NN (15),k-NN (20),DT (10),DT (15),DT (20),NB (10),NB (15),NB (20),MLP (10),MLP (15),MLP (20)
1.0,PCA_075_HOG_256_32x32,10-fold CV,0.694800,0.710500,0.709300,0.612400,0.631400,0.649200,0.695000,0.687000,0.686600,0.463500,0.479800,0.497800
1.0,PCA_075_HOG_256_32x32,70/30,0.687100,0.686300,0.681900,0.652800,0.666600,0.666500,0.683000,0.674800,0.670600,0.444200,0.461700,0.485500
2.0,PCA_075_HOG_128_16x16,10-fold CV,0.684500,0.679000,0.683600,0.634200,0.652800,0.663600,0.677100,0.678200,0.670100,0.534000,0.583900,0.544400
2.0,PCA_075_HOG_128_16x16,70/30,0.683300,0.670800,0.683100,0.657200,0.679200,0.649900,0.655400,0.652000,0.663800,0.499700,0.528500,0.521300
3.0,PCA_090_HOG_256_32x32,10-fold CV,0.682200,0.691100,0.696100,0.587800,0.605000,0.605500,0.638600,0.638800,0.638200,0.449000,0.508900,0.515900
3.0,PCA_090_HOG_256_32x32,70/30,0.677100,0.672700,0.685500,0.599900,0.641600,0.645800,0.654100,0.658300,0.654100,0.427100,0.512500,0.515500
4.0,HOG_256_32x32,10-fold CV,0.687500,0.692000,0.697000,0.662800,0.685900,0.673800,0.703300,0.714500,0.709800,0.696300,0.707500,0.704700
4.0,HOG_256_32x32,70/30,0.655900,0.676700,0.681900,0.699700,0.691600,0.700000,0.737400,0.741600,0.737500,0.694900,0.710700,0.711400
5.0,PCA_090_HOG_128_16x16,10-fold CV,0.645100,0.644600,0.658900,0.630000,0.625900,0.653400,0.639600,0.638000,0.637000,0.520900,0.540600,0.517500
5.0,PCA_090_HOG_128_16x16,70/30,0.645800,0.637000,0.624300,0.624900,0.645300,0.641400,0.620000,0.619700,0.622900,0.534400,0.520800,0.493300
6.0,PCA_075_HOG_128_32x32,10-fold CV,0.670000,0.671200,0.664800,0.618000,0.633900,0.653300,0.697500,0.687500,0.690000,0.501000,0.480400,0.491300
6.0,PCA_075_HOG_128_32x32,70/30,0.662100,0.656000,0.659800,0.683300,0.694900,0.691600,0.737500,0.725000,0.712500,0.567900,0.544600,0.552100
7.0,PCA_090_HOG_128_32x32,10-fold CV,0.648200,0.658300,0.662100,0.650200,0.631200,0.657800,0.680200,0.679300,0.675500,0.458400,0.492900,0.467400
7.0,PCA_090_HOG_128_32x32,70/30,0.630500,0.646700,0.641900,0.662400,0.675000,0.654000,0.691100,0.703300,0.699200,0.525100,0.511900,0.470700
8.0,HOG_128_16x16,10-fold CV,0.644000,0.633900,0.639600,0.647200,0.688400,0.684100,0.732200,0.740000,0.731100,0.717000,0.717600,0.714600
8.0,HOG_128_16x16,70/30,0.637400,0.629100,0.633100,0.631700,0.645800,0.629000,0.749800,0.736900,0.728900,0.723400,0.716200,0.716200
9.0,HOG_128_32x32,10-fold CV,0.632700,0.632800,0.640000,0.638600,0.684700,0.674400,0.704200,0.705400,0.705600,0.357900,0.347700,0.378200
9.0,HOG_128_32x32,70/30,0.615400,0.653300,0.650500,0.628600,0.641600,0.654200,0.737300,0.745600,0.737300,0.323900,0.323900,0.323900
10.0,LBP_256_6R,10-fold CV,0.553300,0.558800,0.563600,0.524900,0.537600,0.549900,0.594000,0.593900,0.591500,0.333300,0.333300,0.333300
10.0,LBP_256_6R,70/30,0.612400,0.644800,0.657200,0.574500,0.616200,0.607700,0.602600,0.581500,0.599000,0.342500,0.342500,0.342500
11.0,PCA_075_HOG_256_16x16,10-fold CV,0.630600,0.649900,0.657300,0.653800,0.673100,0.691700,0.622600,0.624400,0.619900,0.523000,0.501700,0.525000
11.0,PCA_075_HOG_256_16x16,70/30,0.623000,0.623000,0.622900,0.616600,0.658300,0.662500,0.632100,0.628100,0.636100,0.525000,0.453600,0.499400
12.0,LBP_256_12R,10-fold CV,0.539800,0.556200,0.546300,0.544500,0.567100,0.559000,0.594100,0.591600,0.589500,0.333300,0.333300,0.333300
12.0,LBP_256_12R,70/30,0.583300,0.595300,0.595700,0.587500,0.620700,0.587300,0.600500,0.600500,0.601100,0.323900,0.323900,0.323900
NaN,Média =>,NaN,0.642750,0.648750,0.651517,0.625979,0.645575,0.646067,0.669967,0.668579,0.666992,0.492483,0.499100,0.499129
NaN,Desv. Pad. =>,NaN,0.041051,0.038179,0.040154,0.040994,0.038931,0.039114,0.050114,0.051807,0.047998,0.124765,0.125783,0.122551

Análise estatística:

```plain
ANOVA: F=62.5774, p=0.000000
Diferença significativa encontrada. Aplicando Tukey HSD...
Melhor modelo não é significativamente superior ao segundo. Escolhendo por complexidade...
Escolhido: NB(10)
```

> Critério de complexidade: NB < k-NN < DT < MLP e menores estimadores

### Random Forest

In [114]:
display(rf_results)

,Unnamed: 1,Unnamed: 2,Gini (10),Gini (20),Gini (30),Gini (100),Entropy (10),Entropy (20),Entropy (30),Entropy (100)
1.0,PCA_075_HOG_256_32x32,10-fold CV,0.632000,0.647200,0.644200,0.693400,0.618700,0.636100,0.639700,0.691200
1.0,PCA_075_HOG_256_32x32,70/30,0.612800,0.657500,0.679000,0.695800,0.649700,0.631300,0.645100,0.674900
2.0,PCA_075_HOG_128_16x16,10-fold CV,0.595500,0.631100,0.682700,0.697100,0.590100,0.625800,0.631500,0.677000
2.0,PCA_075_HOG_128_16x16,70/30,0.598200,0.637200,0.654000,0.694600,0.575900,0.613400,0.647000,0.703300
3.0,PCA_090_HOG_256_32x32,10-fold CV,0.564600,0.585700,0.582300,0.658200,0.580400,0.612600,0.651300,0.663900
3.0,PCA_090_HOG_256_32x32,70/30,0.591800,0.622400,0.597700,0.683000,0.627300,0.633100,0.637000,0.695800
4.0,HOG_256_32x32,10-fold CV,0.661200,0.688800,0.691800,0.723200,0.652900,0.687700,0.713200,0.721900
4.0,HOG_256_32x32,70/30,0.628400,0.686600,0.653700,0.712500,0.689100,0.728800,0.707300,0.720800
5.0,PCA_090_HOG_128_16x16,10-fold CV,0.549600,0.577000,0.589900,0.639000,0.573800,0.587800,0.614400,0.643000
5.0,PCA_090_HOG_128_16x16,70/30,0.539100,0.570600,0.599600,0.662200,0.461900,0.562300,0.597700,0.661800
6.0,PCA_075_HOG_128_32x32,10-fold CV,0.625700,0.656700,0.669800,0.703500,0.631400,0.638500,0.661100,0.691700
6.0,PCA_075_HOG_128_32x32,70/30,0.625700,0.682300,0.711700,0.737300,0.656400,0.655400,0.716200,0.716600
7.0,PCA_090_HOG_128_32x32,10-fold CV,0.575800,0.636700,0.650900,0.697100,0.592700,0.623900,0.647800,0.669000
7.0,PCA_090_HOG_128_32x32,70/30,0.600500,0.641300,0.683300,0.754200,0.592800,0.663300,0.703000,0.708300
8.0,HOG_128_16x16,10-fold CV,0.604600,0.650400,0.658100,0.720700,0.640200,0.684300,0.689500,0.702700
8.0,HOG_128_16x16,70/30,0.626300,0.670600,0.707800,0.708300,0.635700,0.641000,0.666600,0.699800
9.0,HOG_128_32x32,10-fold CV,0.631500,0.654700,0.668300,0.703000,0.644300,0.683400,0.690900,0.720400
9.0,HOG_128_32x32,70/30,0.679600,0.711900,0.745300,0.724800,0.685900,0.682300,0.711100,0.716000
10.0,LBP_256_6R,10-fold CV,0.541100,0.547500,0.548300,0.553900,0.524400,0.540100,0.556400,0.577600
10.0,LBP_256_6R,70/30,0.599000,0.587300,0.591200,0.616600,0.582300,0.620800,0.603800,0.607400
11.0,PCA_075_HOG_256_16x16,10-fold CV,0.580100,0.625300,0.631400,0.689700,0.564400,0.607600,0.630400,0.703100
11.0,PCA_075_HOG_256_16x16,70/30,0.652900,0.630800,0.652400,0.662500,0.615200,0.695600,0.662200,0.720800
12.0,LBP_256_12R,10-fold CV,0.574500,0.563000,0.567300,0.567900,0.556300,0.575900,0.554800,0.572500
12.0,LBP_256_12R,70/30,0.584900,0.599300,0.616700,0.604000,0.602200,0.616200,0.632900,0.612500
NaN,Média =>,NaN,0.603142,0.631746,0.644892,0.679271,0.606000,0.635300,0.650454,0.678000
NaN,Desv. Pad. =>,NaN,0.036467,0.043307,0.049694,0.050912,0.051162,0.044738,0.045336,0.044982

Análise estatística:

```plain
ANOVA: F=16.4842, p=0.000000
Diferença significativa. Aplicando Tukey HSD...
Melhor não difere significativamente do segundo. Escolhendo por complexidade...
Escolhido: gini(100)
```

> Critério de complexidade: gini < entropy e quantidade de estimadores

### Stacking

In [116]:

display(stacking_results)

,Unnamed: 1,Unnamed: 2,Classificadores (5),Classificadores (10),Classificadores (15),Classificadores (20)
1.0,PCA_075_HOG_256_32x32,10-fold CV,0.714300,0.708000,0.709100,0.704100
1.0,PCA_075_HOG_256_32x32,70/30,0.741600,0.737500,0.720800,0.729200
2.0,PCA_075_HOG_128_16x16,10-fold CV,0.724500,0.713600,0.714000,0.724400
2.0,PCA_075_HOG_128_16x16,70/30,0.677900,0.681500,0.672700,0.682500
3.0,PCA_090_HOG_256_32x32,10-fold CV,0.684000,0.700500,0.684200,0.689500
3.0,PCA_090_HOG_256_32x32,70/30,0.754100,0.754200,0.754200,0.758300
4.0,HOG_256_32x32,10-fold CV,0.711300,0.720400,0.716700,0.720400
4.0,HOG_256_32x32,70/30,0.754100,0.758200,0.758200,0.758200
5.0,PCA_090_HOG_128_16x16,10-fold CV,0.705700,0.685600,0.690500,0.695500
5.0,PCA_090_HOG_128_16x16,70/30,0.670400,0.637200,0.641300,0.648800
6.0,PCA_075_HOG_128_32x32,10-fold CV,0.696000,0.690200,0.689000,0.693100
6.0,PCA_075_HOG_128_32x32,70/30,0.695700,0.704100,0.712500,0.695800
7.0,PCA_090_HOG_128_32x32,10-fold CV,0.704700,0.693800,0.701900,0.698400
7.0,PCA_090_HOG_128_32x32,70/30,0.700000,0.695800,0.695800,0.703900
8.0,HOG_128_16x16,10-fold CV,0.720300,0.714000,0.717700,0.720200
8.0,HOG_128_16x16,70/30,0.724700,0.724700,0.724700,0.728800
9.0,HOG_128_32x32,10-fold CV,0.693000,0.694300,0.693000,0.690300
9.0,HOG_128_32x32,70/30,0.737300,0.737300,0.741500,0.741500
10.0,LBP_256_6R,10-fold CV,0.565300,0.565400,0.564200,0.565400
10.0,LBP_256_6R,70/30,0.611400,0.598600,0.593800,0.593800
11.0,PCA_075_HOG_256_16x16,10-fold CV,0.662900,0.667800,0.667700,0.664700
11.0,PCA_075_HOG_256_16x16,70/30,0.648400,0.649100,0.641000,0.648400
12.0,LBP_256_12R,10-fold CV,0.584300,0.579800,0.579500,0.575900
12.0,LBP_256_12R,70/30,0.581000,0.577900,0.564700,0.573100
NaN,Média =>,NaN,0.685954,0.682896,0.681196,0.683508
NaN,Desv. Pad. =>,NaN,0.053379,0.055030,0.056501,0.056393

Análise estatística:

```plain
ANOVA: F=0.0299, p=0.993046
Sem diferença significativa. Escolhendo o mais simples (menor n).
Escolhido: Stacking(5) (F1=0.6805)
```
> Critério de complexidade: Escolhemos o menor `n` mais perto do F1-score médio.

### Voting

In [ ]:
display(voting_results)

,Unnamed: 1,Unnamed: 2,Classificadores (5),Classificadores (10),Classificadores (15),Classificadores (20)
1.0,PCA_075_HOG_256_32x32,10-fold CV,0.705900,0.706000,0.704200,0.714100
1.0,PCA_075_HOG_256_32x32,70/30,0.712800,0.699800,0.703500,0.699200
2.0,PCA_075_HOG_128_16x16,10-fold CV,0.719500,0.708200,0.722000,0.717000
2.0,PCA_075_HOG_128_16x16,70/30,0.658100,0.666300,0.665500,0.653400
3.0,PCA_090_HOG_256_32x32,10-fold CV,0.697200,0.690800,0.701300,0.702400
3.0,PCA_090_HOG_256_32x32,70/30,0.724100,0.695600,0.737400,0.728100
4.0,HOG_256_32x32,10-fold CV,0.714200,0.720400,0.724400,0.725600
4.0,HOG_256_32x32,70/30,0.729000,0.720700,0.729200,0.737500
5.0,PCA_090_HOG_128_16x16,10-fold CV,0.692900,0.685000,0.705900,0.709500
5.0,PCA_090_HOG_128_16x16,70/30,0.610100,0.651500,0.656800,0.652000
6.0,PCA_075_HOG_128_32x32,10-fold CV,0.660200,0.660500,0.666900,0.670900
6.0,PCA_075_HOG_128_32x32,70/30,0.697900,0.695200,0.686600,0.711700
7.0,PCA_090_HOG_128_32x32,10-fold CV,0.674400,0.663200,0.685700,0.699900
7.0,PCA_090_HOG_128_32x32,70/30,0.707800,0.666700,0.679200,0.691600
8.0,HOG_128_16x16,10-fold CV,0.700800,0.708800,0.717000,0.716900
8.0,HOG_128_16x16,70/30,0.691600,0.699900,0.724900,0.737500
9.0,HOG_128_32x32,10-fold CV,0.676100,0.692900,0.688300,0.687000
9.0,HOG_128_32x32,70/30,0.698700,0.699200,0.716200,0.708000
10.0,LBP_256_6R,10-fold CV,0.578000,0.588800,0.583600,0.583600
10.0,LBP_256_6R,70/30,0.585900,0.591200,0.595000,0.595000
11.0,PCA_075_HOG_256_16x16,10-fold CV,0.623700,0.663900,0.675700,0.676500
11.0,PCA_075_HOG_256_16x16,70/30,0.612500,0.612600,0.639000,0.622900
12.0,LBP_256_12R,10-fold CV,0.559600,0.566500,0.578300,0.574500
12.0,LBP_256_12R,70/30,0.589800,0.565200,0.563000,0.567500
NaN,Média =>,NaN,0.667533,0.667454,0.677067,0.678429
NaN,Desv. Pad. =>,NaN,0.052331,0.047848,0.050869,0.052792

Análise estátistica, copiado do notebook original:

```plain
ANOVA: F=0.6918, p=0.557369
Sem diferença significativa. Escolhendo o mais simples (menor n).
Escolhido: Voting(15) (F1=0.6795)
```

> Escolhemos o menor `n` mais perto do F1-score médio.

### Melhor classificador

Melhores classificadores:

```plain
Melhor Bagging: NB(10) (F1=0.6649)
Melhor RF:      gini(100) (F1=0.6706)
Melhor Stacking: Stacking(5) (F1=0.6805)
Melhor Voting:  Voting(15) (F1=0.6795)
```

Resultado estatístico final:

```plain
ANOVA: F=0.8453, p=0.469546
Sem diferença significativa entre os modelos.
>>> Melhor modelo global (por complexidade): Voting <<<
```

Critério de complexidade: Distância para melhor média e depois, RF < Bagging < Voting < Stacking,